### ISSUE TITLE
converting OPTIONS to LMS_OPTIONS, but use OPTIONS later

### ISSUE THREAD

**Issue by motom001** [pssc/ha-addon-tvheadend#1]
I submit Options as parameter and wonder, why they never reach tvheadend. So I try to understand their way.

1. Options-dialog at home assistant
2. submit to the container as OPTIONS
3. convert at 09-ha-config-to-env.sh from OPTION to LMS_OPTIONS
4. never used again
5. run use instead OPTIONS again, but they seem empty

https://github.com/pssc/ha-addon-tvheadend/blob/6a454f0d2a577ea1a555aa3d2eec6ad4e064bfe7/tvheadend/rootfs/etc/cont-init.d/09-ha-config-to-env.sh
https://github.com/pssc/ha-addon-tvheadend/blob/master/tvheadend/rootfs/etc/services.d/tvhaedend/run#L22

My Option was "--satip_xml http://192.168.178.26:8000/description.xml" and I found the logentry
```
[02:00:25] INFO: Option OPTIONS to LMS_OPTIONS="--satip_xml http://192.168.178.26:8000/description.xml"
```

also by listing all env vars:
```
TERM=xterm-256color
SUPERVISOR_TOKEN=******
SHLVL=1
LMS_OPTIONS="--satip_xml http://192.168.178.26:8000/description.xml"
CWD=/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
S6_CMD_WAIT_FOR_SERVICES=1
DEBIAN_FRONTEND=noninteractive
HAA_NAME=tvheadend
```

but later only:
```
[services.d] starting services
+ LIBSUP=/opt/tvheadend-support/lib/libtvheadend.sh
+ '[' -r /opt/tvheadend-support/lib/libtvheadend.sh ']'
+ . /opt/tvheadend-support/lib/libtvheadend.sh
++ set -o errexit
++ set -o errtrace
++ set -o nounset
++ set -o pipefail
++ readonly LIBLMS_VERSION=0.0.1
++ LIBLMS_VERSION=0.0.1
+++ dirname /opt/tvheadend-support/lib/libtvheadend.sh
++ readonly __LIBLMS_LIB_DIR=/opt/tvheadend-support/lib
++ __LIBLMS_LIB_DIR=/opt/tvheadend-support/lib
+ main
+ echo 'Start tvheadend'
Start tvheadend
+ OPTIONS=
+ PID=635
+ echo -n 635
+ trap stop SIGTERM SIGINT
+ trap '' SIGHUP
+ wait 635
+ echo tvheadend -S -C -c /config/tvheadend/
tvheadend -S -C -c /config/tvheadend/
+ tvheadend -S -C -c /config/tvheadend/
[services.d] done.
```

**Comment by pssc** [comment]
@motom001 this should now be fixed please test.

**Comment by motom001** [comment]
you fixed it 👍
